CREATE TABLE EFFECTIVE_CARE AS SELECT
	PROVIDER_ID, 
	CONDITION, 
	MEASURE_ID, 
	SCORE, 
	SAMPLE, 
	FOOTNOTE, 
	MEASURE_START_DATE, 
	MEASURE_END_DATE
	FROM EFFECTIVE_CARE_RAW;

CREATE TABLE READMISSIONS AS SELECT
	PROVIDER_ID,
 	Measure_ID,
 	Compared_to_national,
 	Denominator,
 	Score,
 	Lower_estimate,
 	Higher_estimate,
 	Footnote,
 	Measure_start_date,
 	Measure_end_date
	FROM READMISSIONS_RAW;

CREATE TABLE SURVEY_RESPONSES AS SELECT
	PROVIDER_ID,
 	HCAHPS_Base_Score,
 	HCAHPS_Consistency_Score 
 	FROM SURVEY_RESPONSES_RAW;